#!/bin/bash

clipman pick --tool=bemenu --tool-args="-p 'Clipboard:' -b --line-height 20 -l 0 --fb '#000000' --ff '#ffffff' --nb '#000000' --nf '#ffffff' --tb '#000000' --hb '#265577' --tf '#ffffff' --hf '#ffffff' --nf '#ffffff' --af '#ffffff' --ab '#000000'"
