#!/bin/bash

entries="Shutdown\nRestart\nLock\nNon-Idle" 
case "$(echo -e $entries | bemenu -b -p "Power:" --line-height 20 -l 0 --fb '#000000' --ff '#ffffff' --nb '#000000' --nf '#ffffff' --tb '#000000' --hb '#265577' --tf '#ffffff' --hf '#ffffff' --nf '#ffffff' --af '#ffffff' --ab '#000000' \
    "Power:" )" in
        Shutdown) exec systemctl poweroff;;
        Restart) exec systemctl reboot;;
        Lock) exec swaylock;;
        Non-Idle) exec ~/.config/sway/scripts/mylock lock-off

esac
