#!/bin/bash

entries="Shutdown\nRestart\nLock\nNon-Idle" 
case "$(echo -e $entries | bemenu -b -p "Power:" --line-height 20 -l 5 --fb '#000000' --ff '#ffffff' --nb '#000000' --nf '#ffffff' --tb '#000000' --hb '#265577' --tf '#ffffff' --hf '#ffffff' --nf '#ffffff' --af '#ffffff' --ab '#000000' \  
    "Power:" )" in
        Shutdown) exec systemctl poweroff;;
        Restart) exec systemctl reboot;;
        Lock) exec swaylock -f -i ~/.local/share/backgrounds/mojave.jpg;;
        Non-Idle) exec mylock lock-off

esac
