#!/bin/bash

# Get available windows
windows=$(swaymsg -t get_tree | jq -r 'recurse(.nodes[]?)|recurse(.floating_nodes[]?)|select(.type=="con"),select(.type=="floating_con")|(.id|tostring)+" "+.app_id+": "+.name')

# Select window with bemenu
selected=$(echo "$windows" | bemenu -b -p "Select Window:" -line-height 20 -l 0 --hb '#285577' --hf '#ffffff' --tf '#ffffff' | awk '{print $1}')

# Tell sway to focus said window
swaymsg [con_id="$selected"] focus
