#!/bin/bash

# Get available windows
windows=$(swaymsg -t get_tree | jq -r 'recurse(.nodes[]?)|recurse(.floating_nodes[]?)|select(.type=="con"),select(.type=="floating_con")|(.id|tostring)+" "+.app_id+": "+.name')

# Select window with bemenu
selected=$(echo "$windows" | bemenu -p "Select Window:" -b --line-height 20 -l 0 --fb '#000000' --ff '#ffffff' --nb '#000000' --nf '#ffffff' --tb '#000000' --hb '#265577' --tf '#ffffff' --hf '#ffffff' --nf '#ffffff' --af '#ffffff' --ab '#000000' | awk '{print $1}')

# Tell sway to focus said window
swaymsg [con_id="$selected"] focus
