# Very much possible tab completion
bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'

shopt -s histappend
shopt -s checkwinsize
shopt -s autocd
shopt -s expand_aliases 

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Bash History
HISTSIZE=100
HISTFILESIZE=200
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/bash/history"

alias ls="ls --color=auto"
alias em="emacsclient -nw"
alias sudo="doas"
alias vim="nvim"
alias imv="imv-wayland"
alias tmn="exec tmux new-session -c ~/Notes/ -s notes -n main"
alias tmc="exec tmux new-session -s hack! -n main"

# enable programmable completion features 
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# the beautiful bash prompt
PS1="\[\033[1;37m\]\w $ \[\033[00m\]" # Setting PS1 to show full path
export PROMPT_DIRTRIM=4 # Trimming path to 4 directories
