# Very much possible tab completion
bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'
bind 'C-y:yes'

shopt -s histappend
shopt -s checkwinsize
shopt -s autocd
shopt -s expand_aliases 

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Bash History
HISTSIZE=100
HISTFILESIZE=200
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/bash/history"

alias ls="ls --color=auto"
alias em="emacsclient -nw"
alias sudo="doas"
alias vim="nvim"
alias imv="imv-wayland"
alias tmn="exec tmux -u new-session -c ~/Notes/ -s notes -n main"
alias tmc="exec tmux -u new-session -s hack! -n main"

# enable programmable completion features 
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export JAVA_HOME="/opt/jdk-21.0.1"
export PATH=$JAVA_HOME/bin:$PATH
export PATH="/opt/jdt-language-server-1.9.0/bin":$PATH

# the beautiful bash prompt
PS1="\[\033[1;37m\]\w $ \[\033[00m\]" # Setting PS1 to show full path
export PROMPT_DIRTRIM=3 # Trimming path to 4 directories
