#!/bin/bash

# Adds `~/.local/bin` to $PATH
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

JAVA_HOME='/opt/jdk-20.0.2/'
GTK_USE_PORTAL=0
export PATH=/opt/jdk-20.0.2/bin:$PATH

export PATH=/usr/local/texlive/2023/bin/x86_64-linux:$PATH

# Clean-up, clean up, everybody everywhere!
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
    fi
fi

if [ -e /home/undefined/.nix-profile/etc/profile.d/nix.sh ]; then . /home/undefined/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
