#+TITLE: Previous Configuration
#+STARTUP: content

* Fonts
 * Install Noto Color Emoji and install source code pro
   font
* Bash
 * In order to source bash at .config location, just link it. I don't know how I
   overlooked this smh
 * profile has environment variables (stuff to add to $PATH and default editor)
  * This has to be linked as the .profile in the home directory in order for it to actually be sourced
* Latex
#+begin_src sh
cd /tmp # working directory of your choice
curl https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz 
zcat < install-tl-unx.tar.gz | tar xf -
cd install-tl-*
perl ./install-tl --no-interaction --scheme=small --no-doc-install --no-src-install # as root or with writable destination
#+end_src

 * Finally, prepend /usr/local/texlive/YYYY/bin/PLATFORM to your PATH,
#+begin_src sh
e.g., /usr/local/texlive/2023/bin/x86_64-linux
#+end_src

 * Changing defaults:
   * The default paper size is a4. If you want the default to be letter, add --paper=letter to the install-tl command.
   * By default, everything is installed (7+GB).
   * To install a smaller scheme, pass --scheme=scheme to install-tl. For example, --scheme=small corresponds to the BasicTeX variant of MacTeX.
   * To omit installation of the documentation resp. source files, pass --no-doc-install --no-src-install to install-tl.
   * To change the main installation directories (rarely needed), add --texdir=/install/dir to the install-tl command. To change the location of the per-user directories (where TEXMFHOME and others will be found), specify --texuserdir=/your/dir.
   * To change anything and everything else, omit the --no-interaction. Then you
     are dropped into an interactive installation menu.
* Neovim
 * Install packer from the website before because it needs it
   #+begin_src sh
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
   #+end_src

 * write and source init.lua first then install packers stuff
 * For pyright and clangd (python and c++ respectively) install npm and node
   (I'm not a fulltime c++ coder so no biggie)
* Programming Languages
** Rust
 * Install via rustup (requires curl)
   #+begin_src sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
   #+end_src

** Java
 * Download JDK from reputable source
 * untar/unzip in some direcotry (ex. /usr or /opt)
 * Add to path (should already be in /bash/profile)
** Python
 * Install python3 from package manager
** C/C++
 * Install npm for nvim stuff
 * Comes by default
 * I may be forgetting something... nope. Oh wait! you gotta find out how to install npm urself lol >.<
* Nix packages
#+begin_src sh
sh <(curl -L https://nixos.org/nix/install) --daemon
#+end_src
 * bemenu-0.6.15
 * brightnessctl-0.5.1
 * clipman-1.6.2
 * emacs-pgtk-29.1
 * gammastep-2.0.9
 * keyd-2.4.2
 * lf-30
 * neovim-0.9.1
 * swaynag-battery-0.2.0
 * swayr-0.26.1
 * warpd-1.3.5
 * yt-dlp-2023.7.6
 * *keyd* - this isn't configured but will be :)
* Debian packages
 * imv (image viewer)
 * tmux
 * latex
 * foot
 * i3status
 * mpv
 * qutebrowser
 * pulseaudio
 * alsa-utils
 * sway
 * swaylock
 * swaynag
 * zathura
 * wl-clipboard
 * ly
   * Enable cmatrix and big clock
 * languagetool
 * jq
